name: "Docker"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    paths_ignore:
      - "*.md"
      - "Makefile"
      - "ssl"

jobs:
  docker:
    runs-on: "ubuntu-22.04"
    steps:
      - id: "checkout"
        name: "Checkouts the Git repository"
        uses: "actions/checkout@v2"
      - id: "qemu"
        name: "Installs the QEMU binaries"
        uses: "docker/setup-qemu-action@v1"
        with:
          platforms: "all"
      - id: "buildx"
        name: "Installs the Buildx CLI plugin"
        uses: "docker/setup-buildx-action@v1"
      - id: "cache"
        name: "Caches the Docker building layers"
        uses: "actions/cache@v2"
        with:
          path: "/tmp/.buildx-cache"
          key: "${{ runner.os }}-buildx-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-buildx-
